# -*- coding: utf-8 -*-
"""Titanic Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jZkY4-BWUSuIL3EirFlZ2oyKecVYqm4
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
dt=pd.read_csv('/content/Titanic-Dataset.csv')
dt

dt.isnull().sum()

dt.head()

dt.tail()

# Fill missing values for 'Age' with the median age
dt['Age'].fillna(dt['Age'].median(), inplace=True)

# Fill missing values for 'Embarked' with the mode
dt['Embarked'].fillna(dt['Embarked'].mode()[0], inplace=True)

# Drop 'Cabin' as it has too many missing values
dt.drop('Cabin', axis=1, inplace=True)

# Convert categorical variables to numerical ones
dt = pd.get_dummies(dt, columns=['Sex', 'Embarked'], drop_first=True)
dt = pd.get_dummies(dt, columns=['Name'], drop_first=True)

# Define the feature columns and target variable
x = dt[['PassengerId','Pclass',,'Sex_male','Age','SibSp','Parch','Ticket','Fare','Embarked_Q','Embarked_S']]
y = dt['Survived']

# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)